#!/bin/bash

source ./settings

# ---------------------------------------- Obtain an access token ---------------------------------------- #
RESPONSE=$(curl -s --request POST \
	--url "https://api.intra.42.fr/oauth/token" \
	--header "content-type: application/json" \
	--data "{
		\"grant_type\": \"client_credentials\",
		\"client_id\": \"$UID_42\",
		\"client_secret\": \"$SECRET_42\"
	}")
if [[ "$RESPONSE" == *"error"* ]]; then
	printf "${BOLD}${RED}Error: Failed to obtain access token (check UID and SECRET)\n${DEF}"
	exit 1
fi

ACCESS_TOKEN=$(echo $RESPONSE | jq -r '.access_token')
if [ -z "$ACCESS_TOKEN" ]; then
	printf $BOLD$RED"Error: Failed to obtain access token (check UID and SECRET)\n"$DEF
	exit 1
fi

CAMPUS_JSON=$(curl -s -H "Authorization: Bearer $ACCESS_TOKEN" "https://api.intra.42.fr/v2/campus")
if [ -z "$1" ]; then
	printf "${BOLD}${RED}Error: Please set the name of your 42 Campus\n${DEF}"
	exit 1
else
	CAMPUS_ID=$(echo "$CAMPUS_JSON" | jq --arg name "$1" '.[] | select(.name == $name) | .id')
	if [ -z "$CAMPUS_ID" ]; then
		printf "${BOLD}${RED}Error: Not an existing campus please check it again\n${DEF}"
		exit 1
	fi
fi

printf "42 $YELLOW$1$DEF ID is $BOLD$PURPLE$CAMPUS_ID$DEF\n"
