#!/bin/bash

source functions

printf "$BOLD$PURPLE
                     .__                          __    
______   ____   ____ |  |   ____________    ____ |  | __
\\____ \\ /  _ \\ /  _ \\|  |   \\_  __ \\__  \\  /    \\|  |/ /
|  |_> >  <_> |  <_> )  |__  |  | \\// __ \\|   |  \\    < 
|   __/ \\____/ \\____/|____/  |__|  (____  /___|  /__|_ \\
|__|                                    \\/     \\/     \\/
$DEF

╭─────────────────────────────────────────────────────────────╮
│                                                             │
│    First create a 42 application following this link:       │
│    https://api.intra.42.fr/apidoc/guides/getting_started    │
│                                                             │
╰─────────────────────────────────────────────────────────────╯


"


printf "${GRAY}Paste your application UID:${DEF} "
read -p "" UID_42 
printf "${GRAY}Paste your application SECRET:${DEF} "
read -p "" SECRET_42
printf "${DEF}\n"

# ---------------------------------------- Obtain an access token ---------------------------------------- #
RESPONSE=$(curl -s --request POST \
	--url "https://api.intra.42.fr/oauth/token" \
	--header "content-type: application/json" \
	--data "{
		\"grant_type\": \"client_credentials\",
		\"client_id\": \"$UID_42\",
		\"client_secret\": \"$SECRET_42\"
	}")
if [[ "$RESPONSE" == *"error"* ]]; then
	printf "${BOLD}${RED}Error: Failed to obtain access token (check UID and SECRET)\n${DEF}"
	exit 1
fi

ACCESS_TOKEN=$(echo $RESPONSE | jq -r '.access_token')
if [ -z "$ACCESS_TOKEN" ]; then
	printf "${BOLD}${RED}Error: Failed to obtain access token (check UID and SECRET)\n${DEF}"
	exit 1
fi


# ---------------------------------------- Get Basic User Info ---------------------------------------- #
printf "${GRAY}Type your login to fetch campus information:${DEF} "
read -p "" LOGIN
printf "\n"

PR_PATH=$(pwd)

USER_DATA=$(curl -g -s -H "Authorization: Bearer $ACCESS_TOKEN" "https://api.intra.42.fr/v2/users/$LOGIN")

echo $USER_DATA | jq > user_info
POOL_YEAR=$(cat user_info | jq ".pool_year")
POOL_MONTH=$(cat user_info | jq ".pool_month")
CAMPUS_ID=$(cat user_info | jq ".campus[].id")

printf "
# VARIABLES
IS_INIT=1
UID_42=\"$UID_42\"
SECRET_42=\"$SECRET_42\"
CAMPUS_ID=\"$CAMPUS_ID\"
POOL_YEAR=$POOL_YEAR
POOL_MONTH=$POOL_MONTH
PR_PATH=\"$PR_PATH\"
LOGIN=\"$LOGIN\"
" > settings

rm user_info
