#!/bin/bash

source .env
source functions

clear

printf "$BOLD$PURPLE
                     .__                          __    
______   ____   ____ |  |   ____________    ____ |  | __
\\____ \\ /  _ \\ /  _ \\|  |   \\_  __ \\__  \\  /    \\|  |/ /
|  |_> >  <_> |  <_> )  |__  |  | \\// __ \\|   |  \\    < 
|   __/ \\____/ \\____/|____/  |__|  (____  /___|  /__|_ \\
|__|                                    \\/     \\/     \\/
$DEF
"

# ---------------------------------------- Obtain an access token ---------------------------------------- #
RESPONSE=$(curl -s --request POST \
	--url "https://api.intra.42.fr/oauth/token" \
	--header "content-type: application/json" \
	--data "{
		\"grant_type\": \"client_credentials\",
		\"client_id\": \"$UID_42\",
		\"client_secret\": \"$SECRET_42\"
	}")
if [[ "$RESPONSE" == *"error"* ]]; then
	printf "${BOLD}${RED}Error: Failed to obtain access token (check UID and SECRET)\n${DEF}"
	exit 1
fi

ACCESS_TOKEN=$(echo $RESPONSE | jq -r '.access_token')

# ------------------------------------ Check if the variables are set ------------------------------------ #
if [ -z "$ACCESS_TOKEN" ]; then
	printf $BOLD$RED"Error: Failed to obtain access token (check UID and SECRET)\n"$DEF
	exit 1
elif [ -z "$CAMPUS_ID" ]; then
	printf $BOLD$RED"Error: Please set an existing campus ID (you can use campus_id.sh)\n"$DEF
	exit 1
elif [ -z "$POOL_MONTH" ]; then
	printf $BOLD$RED"Error: Please set a pool month\n"$DEF
	exit 1
elif [ -z "$POOL_YEAR" ]; then
	printf $BOLD$RED"Error: Please set a pool year\n"$DEF
	exit 1
fi

printf "\n${BOLD}Pool month:${DEF} $POOL_MONTH\n${BOLD}Pool year:${DEF} $POOL_YEAR\n\n"

# --------------------------------------- Refresh the ranks or not --------------------------------------- #
if [ ! -e "./users" ] || [ ! -s "./users" ]; then
	REFRESH=1
else
	printf "${BOLD}${GRAY}$(tail -n 1 users)\n\n${DEF}"
	while : ; do
		read -p "Do you want to refresh ? (Y/n): " REFRESH
		case $REFRESH in
			[Yy]*)
				REFRESH=1
				echo ""
				break;;
			[Nn]*)
				REFRESH=0
				echo ""
				break;;
			*)
				echo "Please answer yes (y) or no (n)."
				;;
		esac
	done
fi

if [ "$REFRESH" -eq 1 ]; then
	echo -n "" > users
	ALL_PAGE_USERS=$(fetch_users_by_pool "$POOL_MONTH" "$POOL_YEAR")
	if [ $? -ne 0 ]; then
		printf $BOLD$RED"Error: No students found for the specified pool month/year.\n"$DEF
		exit 1
	fi
	fetch_users_data "$ALL_PAGE_USERS"
	if [ $? -ne 0 ]; then
		printf $BOLD$RED"Error: Failed to fetch students' data\n"$DEF
		exit 1
	fi
	echo "Last updated: $(date +%Y/%m/%d-%H:%M:%S)" >> users
	printf "\n\n"
fi

# --------------------------------------------- PRINT RANKS ---------------------------------------------- #
read -p "Check login: " LOGIN
echo ""
printf "${BOLD}${RED}RANK  LOGIN      LVL\n${DEF}"
# Read from the file, sort in reverse by the second field (level), and format the output
RANK_USERS=$(head -n -2 users | sort -t: -k2 -nr)
echo "$RANK_USERS" | awk -F": " -v bold="$BOLD" -v def="$DEF" -v green="$GREEN" -v yellow="$YELLOW" \
	-v gray="$GRAY" -v login="$LOGIN"\
	'BEGIN {rank=1} {
		if ($1 == login) {
			printf bold green "%-5s " green "%-10s " yellow "%0.4s\n" def, rank++, $1, $2
		} else {
			printf bold green "%-5s " gray "%-10s " yellow "%0.4s\n" def, rank++, $1, $2
		}
	}'
