#!/bin/bash

# ESSENTIAL VARIABLES
UID_42="" # your application's UID
SECRET_42="" # your application's SECRET
CAMPUS_ID="" # execute ./campus_id YOUR_CAMPUS_CITY if you don't know your campus id
POOL_MONTH="" # Format eg: "february"
POOL_YEAR="" # Format: "yyyy"
PR_PATH="" # pwd of the respository

# COLORS FOR DISPLAY
RED="\033[38;5;124m"
PURPLE="\033[38;5;171m"
YELLOW="\033[38;5;227m"
GREEN="\033[38;5;119m"
DEF="\033[0m"
BOLD="\033[1m"
GRAY="\033[2;37m"
